name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.234.118.198
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/Projects/fastapi-app-docker-demo
            git pull origin master
            cd fastapi-app/
            COMMIT_HASH=$(git log -1 --format=%h)
            IMAGE_TAG=fastapi_app:$COMMIT_HASH
            docker build -t $IMAGE_TAG --build-arg GIT_COMMIT=$COMMIT_HASH .
            docker stop fastapi_app || true
            docker rm fastapi_app || true
            docker run -d --name fastapi_app -p 87:80 $IMAGE_TAG